<?php

namespace DoctrineORMModule\Proxy\__CG__\LSTicket\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Ticket extends \LSTicket\Entity\Ticket implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setDateBegin()
    {
        $this->__load();
        return parent::setDateBegin();
    }

    public function getDateBegin()
    {
        $this->__load();
        return parent::getDateBegin();
    }

    public function setDateEnd($dateEnd)
    {
        $this->__load();
        return parent::setDateEnd($dateEnd);
    }

    public function getDateEnd()
    {
        $this->__load();
        return parent::getDateEnd();
    }

    public function setDateEstimated($dateEstimated)
    {
        $this->__load();
        return parent::setDateEstimated($dateEstimated);
    }

    public function getDateEstimated()
    {
        $this->__load();
        return parent::getDateEstimated();
    }

    public function setSought($sought)
    {
        $this->__load();
        return parent::setSought($sought);
    }

    public function getSought()
    {
        $this->__load();
        return parent::getSought();
    }

    public function setActive($active)
    {
        $this->__load();
        return parent::setActive($active);
    }

    public function getActive()
    {
        $this->__load();
        return parent::getActive();
    }

    public function setCategoryTicket(\LSCategoryticket\Entity\CategoryTicket $categoryTicket = NULL)
    {
        $this->__load();
        return parent::setCategoryTicket($categoryTicket);
    }

    public function getCategoryTicket()
    {
        $this->__load();
        return parent::getCategoryTicket();
    }

    public function setPriority(\LSPriority\Entity\Priority $priority = NULL)
    {
        $this->__load();
        return parent::setPriority($priority);
    }

    public function getPriority()
    {
        $this->__load();
        return parent::getPriority();
    }

    public function setUser(\LSUser\Entity\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'dateBegin', 'dateEnd', 'dateEstimated', 'sought', 'active', 'categoryTicket', 'priority', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}