tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
filter:
    paths: 
        - 'module/Application/src/Application/*'
    excluded_paths:
        - 'vendor/*'
        - 'bin/*'
        - 'doc/*'
        - 'config/*'
        - 'data/*'
        - 'public/*'
        - 'module/Application/src/Application/Fixture*'
        - 'module/Application/tests/*'
        - 'module/Application/language/*'
        - 'module/Application/config/*'
        - 'module/Application/view/*'