tools:
    php_sim: true
    php_pdepend:
        enabled: true
        command: pdepend
        excluded_dirs:
            - 'vendor'
    php_analyzer:
        enabled: true
        extensions:
            - php
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'bin/*'
                - 'doc/*'
                - 'config/*'
                - 'data/*'
                - 'public/*'
                - 'module/Application/tests/*'
                - 'module/Application/language/*'
                - 'module/Application/config/*'
                - 'module/Application/view/*'
    php_code_sniffer:
        enabled: true
        command: phpcs
        config:
            standard: PSR2
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'module/Application/tests/*'