tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_cs_fixer:
        extensions:
            - php
        command: php-cs-fixer
        enabled: true
        config:
            level: all
    php_cpd:
        command: phpcpd
        min_lines: 5
        min_tokens: 70
        names:
            # Default:
            - '*.php'
        enabled: true
    external_code_coverage: true
filter:
    paths:
        - 'module/Application/src/Application/*'
    excluded_paths:
        - 'vendor/*'
        - 'bin/*'
        - 'doc/*'
        - 'config/*'
        - 'data/*'
        - 'public/*'
        - 'module/Application/src/Application/Fixture*'
        - 'module/Application/tests/*'
        - 'module/Application/language/*'
        - 'module/Application/config/*'
        - 'module/Application/view/*'