language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - php composer.phar self-update
  - php composer.phar install --prefer-source --dev --no-interaction
script:
  - bin/phpunit -c module/Application/tests/ --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="6c85a73c632cba80dea52b108761f3e96aa41c0ffaacbdd164a145c368f83285" --format=php-clover coverage.clover