<?php

namespace LSCategoryticket\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryTicketRepository extends EntityRepository
{
}
