<?php

namespace LSCategoryticket\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryTicketRepository extends EntityRepository
{
    /**
     * fetchPairs
     *
     * Monta um array com o ID e a descrição,
     *
     * @return array
     */
    public function fetchPairs ()
    {
        $categoryTickets = $this->findAll ();
        $array = array();

        foreach ( $categoryTickets as $categoryTicket )
            $array[$categoryTicket->getId ()] = $categoryTicket->getDescription ();

        return $array;

    }
}
