<?php

namespace LSInteraction\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IntegrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegrationRepository extends EntityRepository
{
}
