<!--Load the AJAX API-->
<script type="text/javascript" src="/js/jsapi.js"></script>
<script type="text/javascript">

  // Load the Visualization API and the piechart package.
  google.load('visualization', '1.0', {'packages':['corechart']});

  // Set a callback to run when the Google Visualization API is loaded.
  google.setOnLoadCallback(drawChart);

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart() {

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Topping');
    data.addColumn('number', 'Slices');
    data.addRows([
      ['Aberto', <?php echo $this->ticketOpen; ?>],
      ['Andamento', <?php echo $this->ticketOngoing; ?>],
      ['Fechados', <?php echo $this->ticketResolved; ?>]
    ]);

    // Set chart options
    var options = {'width':360, 'height':300 };

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.PieChart(document.getElementById('pizza'));
    chart.draw(data, options);
  }
</script>

<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      [ '', 'Aberto', 'Andamento', 'Fechados'],
      [  'quantidade', <?php echo $this->ticketOpen; ?>, <?php echo $this->ticketOngoing; ?>, <?php echo $this->ticketResolved; ?>,]
    ]);

    var options = { hAxis: {title: '', titleTextStyle: {color: 'red'}}
    };

    var chart = new google.visualization.ColumnChart(document.getElementById('barra'));
    chart.draw(data, options);
  }
</script>

<div class="row">

  <div class="span4 box-home">
        <div class="navbar">
          <div class="navbar-inner">
              <p class="navbar-home"><i class=" icon-bar-chart icon-large"></i> <strong>Gráfico em Pizza (geral)</strong></p>
          </div>
        </div>

        <div class="thumbnail ticket-home">
          <!--Div that will hold the pie chart-->
          <div id="pizza"></div>
        </div>
  </div>

  <div class="span6 box-home">
        <div class="navbar">
          <div class="navbar-inner">
              <p class="navbar-home"><i class=" icon-bar-chart icon-large"></i> <strong>Gráfico em Barras (geral)</strong></p>
          </div>
        </div>
        <div class="thumbnail ticket-home">
          <div id="barra" style="width: 560px; height: 300px;"></div>
        </div>
  </div>

</div>

<br /><br />
<div class="row">
  <div class="span4 offset3">
      <a class="btn btn-info active-listservice" href="#" data-toggle="tooltip" data-placement="top" data-original-title="Imprimir Ticket's em abertos" ><i class=" icon-print"></i> Aberto</a>
      <a class="btn btn-info active-listservice" href="#" data-toggle="tooltip" data-placement="top" data-original-title="Imprimir Ticket's em andamento" ><i class=" icon-print"></i> Andamento</a>
      <a class="btn btn-info active-listservice" href="#" data-toggle="tooltip" data-placement="top" data-original-title="Imprimir Ticket's fechado" ><i class=" icon-print"></i> Fechado</a>
  </div>
</div>