<!--Load the AJAX API-->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

  // Load the Visualization API and the piechart package.
  google.load('visualization', '1.0', {'packages':['corechart']});

  // Set a callback to run when the Google Visualization API is loaded.
  google.setOnLoadCallback(drawChart);

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart() {

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Topping');
    data.addColumn('number', 'Slices');
    data.addRows([
      ['Em andamento', 3],
      ['Em aberto', 1],
      ['Olives', 1],
      ['Zucchini', 1],
      ['Pepperoni', 2]
    ]);

    // Set chart options
    var options = {'width':459, 'height':300 };

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.PieChart(document.getElementById('pizza'));
    chart.draw(data, options);
  }
</script>

<script type="text/javascript">
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Year', 'Sales', 'Expenses'],
      ['2004',  1000,      400],
      ['2005',  1170,      460],
      ['2006',  660,       1120],
      ['2007',  1030,      540]
    ]);

    var options = { hAxis: {title: 'Mensal', titleTextStyle: {color: 'red'}}
    };

    var chart = new google.visualization.ColumnChart(document.getElementById('barra'));
    chart.draw(data, options);
  }
</script>

<div class="row">

  <div class="span5 box-home">
        <div class="navbar">
          <div class="navbar-inner">
              <p class="navbar-home"><i class=" icon-bar-chart icon-large"></i> <strong>Gráfico em Pizza</strong></p>
          </div>
        </div>

        <div class="thumbnail ticket-home">
          <!--Div that will hold the pie chart-->
          <div id="pizza"></div>
        </div>
  </div>

  <div class="span5 box-home">
        <div class="navbar">
          <div class="navbar-inner">
              <p class="navbar-home"><i class=" icon-bar-chart icon-large"></i> <strong>Ticket's em andamento</strong></p>
          </div>
        </div>
        <div class="thumbnail ticket-home">
          <div id="barra" style="width: 459px; height: 300px;"></div>
        </div>
  </div>

</div>