<link rel="stylesheet" type="text/css" media="print" href="/css/print.css">


<?php $this->plugin("dateFormat")->setTimezone("America/Campo_Grande")->setLocale("pt_BR");?>
<table class="table table-striped table-condensed table-bordered">
  <caption>Relatorio Ticket's <br /><br /><a class="btn btn-info print" href="#" onclick="window.print();return false"><i class="icon-print"></i> Imprimir</a></caption>
  <thead>
    <tr>
      <th class="span1">#</th>
      <th>Titulo</th>
      <th>Solicitante</th>
      <th>Data abertura</th>
      <th>Previsão</th>
      <th>Prioridade</th>
      <th>Categoria</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->ticket as $ticket): ?>
    <tr>
      <th><?php echo $ticket->getId(); ?></th>
      <th><?php echo $ticket->getTitle(); ?></th>
      <th><?php echo $ticket->getSought(); ?></th>
      <th><?php echo $this->dateFormat($ticket->getDateBegin(), IntlDateFormatter::SHORT); ?></th>
      <th><?php echo $this->dateFormat($ticket->getDateEstimated(), IntlDateFormatter::SHORT); ?></th>
      <th><?php echo $ticket->getPriority()->getDescription(); ?></th>
      <th><?php echo $ticket->getCategoryTicket()->getDescription(); ?></th>
      <th><?php if ($ticket->getActive() == 1){echo "<span class=\"label label-info\">Aberto</span>";}else{echo "<span class=\"label\">Fechado</span>";} ?></th>
    <?php endforeach; ?>
  </tbody>
</table>






