<?php

namespace LSPriority\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriorityRepository extends EntityRepository
{
}
