<?php

namespace LSTicket\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{

    public function TotalMyTicket($user)
    {        
        $query = "SELECT COUNT(t.id) FROM LSTicket\Entity\Ticket t WHERE t.user = {$user} AND t.active = TRUE AND t.dateEnd IS NULL";
        
        return $this->_em->createQuery($query)->getResult();
        
    }
}
