<?php $this->plugin("dateFormat")->setTimezone("America/Campo_Grande")->setLocale("pt_BR");?>

<div class="row">

  <div class="span5 box-home">
        <div class="navbar">
          <div class="navbar-inner">
              <p class="navbar-home"><i class="icon-reorder icon-large"></i> <strong>Dados do Ticket #<?php echo $this->ticket->getId()?></strong></p>
          </div>
        </div>

        <div class="thumbnail ticket-home">

            <h4><?php echo $this->ticket->getTitle(); ?></h4>
            <p><strong>Solicitante: </strong><?php echo $this->ticket->getSought(); ?></p>
            <p><strong>Data de abertura: </strong><?php echo $this->dateFormat($this->ticket->getDateBegin(), IntlDateFormatter::SHORT); ?></p>
            <p><strong>Categoria: </strong><?php echo $this->ticket->getCategoryTicket()->getDescription(); ?></p>

            <?php

                $form = $this->form;

                $this->formElementErrors ()
                        ->setMessageOpenFormat ('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">×</button>')
                        ->setMessageCloseString ('</div>')
                        ->render ($form);

                $form->setAttribute ('action', $this->url ('interaction/default', array('controller' => 'interaction', 'action' => 'new', 'id' => $this->ticket->getId())));

                $form->prepare ();

                echo $this->form ()->openTag ($form);

                echo $this->formCollection ($form);

                echo $this->form ()->closeTag ();
            ?>
        </div>
  </div>

   <div class="span5 box-home offset2">
        <div class="navbar">
          <div class="navbar-inner">
              <p class="navbar-home"><i class=" icon-lightbulb icon-large"></i> <strong>Interaçōes</strong></p>
          </div>
        </div>

        <div class="thumbnail ticket-home">
<?php //\Zend\Debug\Debug::dump($this->description[0]->getUser()->getName() );die; ?>


          <?php foreach ($this->description as $value): ?>
            <div class="thumbnail" style="background:#fff">
                <strong><?php echo $value->getUser()->getName(); ?>: </strong>
                <p><?php echo $value->getDescription() ?></p>
            </div>
          <?php endforeach; ?>

      </div>
  </div>

</div>