<?php

namespace LSTypeuser\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeUserRepository extends EntityRepository
{

    /**
     * fetchPairs
     *
     * Monta um array com o ID e a descrição,
     *
     * @return array
     */
    public function fetchPairs ()
    {
        $categoryTickets = $this->findAll ();
        $array = array();

        foreach ( $categoryTickets as $categoryTicket )
            $array[$categoryTicket->getId ()] = $categoryTicket->getDescription ();

        return $array;

    }

    /**
     * fetchAllTypeUserActive
     *
     * Retorna todos os tipos de usuarios ativos
     *
     * @return array
     */
    public function fetchAllTypeUserActive()
    {
        $query = "SELECT t.id, t.description FROM LSTypeuser\\Entity\\TypeUser t WHERE t.active = true";

        return $this->_em->createQuery($query)->getResult();
    }
}
