<?php

namespace LSTypeuser\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeUserRepository extends EntityRepository
{

    /**
     * fetchPairs
     * 
     * Monta um array com o ID e a descrição,
     * 
     * @return array
     */
    public function fetchPairs ()
    {
        $typeUsers = $this->findAll ();
        $array = array();

        foreach ( $typeUsers as $typeUser )
            $array[$typeUser->getId ()] = $typeUser->getDescription ();

        return $array;

    }

}
