<?php

namespace LSBase\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserCategoryTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCategoryTicketRepository extends EntityRepository
{
    /**
     * fetchAllTypeUserActive
     *
     * Retorna todos os tipos de usuarios ativos
     *
     * @return array
     */
    public function fetchAllUserCategoryTicket($id)
    {
        $query = "SELECT tu.description as roles, ct.description as permissions FROM LSBase\\Entity\\UserCategoryTicket uct JOIN uct.user u JOIN  u.typeUse tu JOIN uct.categoryTicket ct  WHERE tu.active = true AND u.id NOT IN(3) AND u.active = true AND ct.active = true AND u.id = {$id}";

        return $this->_em->createQuery($query)->getResult();
    }
}
