<?php

namespace LSBase\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserCategoryTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCategoryTicketRepository extends EntityRepository
{
    /**
     * fetchAllTypeUserActive
     *
     * Retorna todos os tipos de usuarios ativos
     *
     * @return array
     */
    public function fetchAllUserCategoryTicket()
    {
        $query = "SELECT ct.description FROM LSBase\\Entity\\UserCategoryTicket uct JOIN LSCategoryticket\\Entity\\CategoryTicket ct uct.categoryTicket ct  JOIN LSUser\\Entity\\User us uct.user us WHERE uct.user = 3";

        return $this->_em->createQuery($query)->getResult();
    }
}
