<?php

namespace LSBase\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * USerCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCategoryRepository extends EntityRepository
{
}
