<?php echo $this->doctype(); ?>
<html class="bg-black">
<head lang="en">
    <meta charset="UTF-8">
    <?php echo $this->headTitle($this->translate('Recovery Password')); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php echo $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/AdminLTE.css')
        ->prependStylesheet($this->basePath() . '/css/ionicons.min.css')
        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>
</head>
    <body class="bg-black">
        <div class="form-box" id="login-box">
            <div class="header"><?php echo $this->translate('Recovery Password'); ?></div>
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('user').'/recovery-password')->prepare();

                $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageCloseString('</small>')->render($form);
            ?>
            <?php echo $this->form()->openTag($form) ?>
                <div style="padding: 10px 20px; color: #444" class="bg-gray">

                    <?php
                        echo $this->FlashMessenger()->render('error');
                        echo $this->FlashMessenger()->render('success');
                    ?>

                    <div class="form-group<?php if($this->formElementErrors($form->get('email'))) echo " has-error" ?>">
                        <label class="control-label" <?php if($this->formElementErrors($form->get('email'))) echo ' for="inputError"' ?>>
                            <?php if($this->formElementErrors($form->get('email'))) echo '<i class="fa fa-times-circle-o"></i> ' ?><?php echo $form->get('email')->getLabel() ?>
                        </label>
                        <?php
                            $attr = ['class' => 'form-control', 'placeholder' => 'Enter you e-mail'];
                            if($this->formElementErrors($form->get('email'))) {
                                $attr = array_merge($attr, ['id' => 'inputError']);
                            }
                        ?>
                        <?php echo $this->formInput($form->get('email')->setAttributes($attr)) . $this->formElementErrors($form->get('email')) ?>
                    </div>
                </div>
                <div class="footer">
                    <?php echo $this->formButton($form->get('recovery')); ?>
                    <a href="<?php echo $this->url('zfcuser/login'); ?>" class="text-center">Return to login</a>
                </div>
            <?php echo $this->form()->closeTag() ?>
        </div>
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', 'text/javascript', array('conditional' => 'lt IEz 9',))
            ->prependFile('https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    </body>
</html>
