<?php $user = $this->UserIdentity("LS"); ?>

<?php echo $this->doctype (); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle ('ListService - Gestão de atendimento')->setSeparator (' - ')->setAutoEscape (false) ?>

        <?php echo $this->headMeta ()->appendName ('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Scripts -->
        <?php

        echo $this->headScript ()->prependFile ($this->basePath () . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile ($this->basePath () . '/js/bootstrap.min.js')
                ->prependFile ($this->basePath () . '/js/jquery.min.js')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink (array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath () . '/images/favicon.ico'))
                ->prependStylesheet ($this->basePath () . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet ($this->basePath () . '/css/style.css')
                ->prependStylesheet ($this->basePath () . '/css/bootstrap.min.css')
        ?>


        <link rel="stylesheet" href="/css/font-awesome.min.css">

        <script type="text/javascript">
            $(document).ready(function(){
                $('.home-link').click(function(){
                    $('.home-link').parent().removeClass('active');
                    $(this).parent().addClass('active');
                });

                $('.active-listservice').tooltip();
            });
        </script>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <h1>
                        <object data="/images/logo-top.svg" type="image/svg+xml" width="180" height="45">Not Support SVG.</object>
                    </h1>

                    <div class="nav-collapse collapse">
                        <ul class="nav">

                            <li><a class="home-link" href="<?php echo $this->url ('home', array('controller' => 'home'))?>">Home</a></li>

                            <li class="dropdown">
                                    <a class="dropdown-toggle home-link" data-toggle="dropdown" href="#">Ticket</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->url ('ticket/default', array('controller' => 'ticket'))?>"><i class="icon-inbox"></i> Menus Ticket's <i class="badge badge-inverse"> <?php echo $this->TotalMyTicket(); ?></i></a></li>
                                        <li><a href="<?php echo $this->url ('ticket/default', array('controller' => 'ticket', 'action' => 'new'))?>"><i class="icon-edit"></i> Cadastrar</a></li>
                                        <li><a href=""><i class="icon-bookmark-empty"></i> Resolvidos <i class="badge badge-success"> <?php echo $this->TotalMyTicketResolved();?></i></a></li>
                                        <li><a href=""><i class="icon-bookmark"></i> Em andamento <i class="badge badge-warning"> <?php echo $this->TotalMyTicketOngoing(); ?></i></a></li>
                                    </ul>
                            </li>

                            <?php if (($user['category_id'] == "1") || ($user['category'] == 'Administrador')): ?>

                                <li class="dropdown">
                                        <a class="dropdown-toggle home-link" data-toggle="dropdown" href="#">Categoria de Ticket</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?php echo $this->url ('category-ticket/default', array('controller' => 'category-ticket'))?>"><i class="icon-inbox"></i> Todas as Categoria</a></li>
                                            <li><a href="<?php echo $this->url ('category-ticket/default', array('controller' => 'category-ticket', 'action' => 'new'))?>"><i class="icon-asterisk"></i> Cadastrar</a></li>
                                        </ul>
                                </li>

                                <li class="dropdown">
                                        <a class="dropdown-toggle home-link" data-toggle="dropdown" href="#">Prioridade</a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?php echo $this->url ('priority/default', array('controller' => 'priority'))?>"><i class="icon-inbox"></i> Todas as Prioridades</a></li>
                                            <li><a href="<?php echo $this->url ('priority/default', array('controller' => 'priority', 'action' => 'new'))?>"><i class="icon-asterisk"></i> Cadastrar</a></li>
                                        </ul>
                                </li>

                                <li class="dropdown">
                                    <a class="dropdown-toggle home-link" data-toggle="dropdown" href="#">Usuários</i></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->url ('user/default', array('controller' => 'user'))?>"><i class="icon-group"></i> Todos usuários</a></li>
                                        <li><a href="<?php echo $this->url ('user/default', array('controller' => 'user', 'action' => 'new')); ?>"><i class="icon-edit"></i> Cadastrar</a></li>
                                        <li class="divider"></li>
                                        <li><a href="<?php echo $this->url('type-user/default', array('controller' => 'type-user')); ?>"><i class="icon-asterisk"></i> Todas as categoria de usuário</a></li>
                                        <li><a href="<?php echo $this->url('type-user/default', array('controller' => 'type-user', 'action' => 'new')); ?>"><i class="icon-asterisk"></i> Cadastrar Categoria de usuário</a></li>
                                    </ul>
                                </li>

                                <li class="dropdown">
                                    <a class="dropdown-toggle home-link" data-toggle="dropdown" href="#">Relatórios</a>
                                    <ul class="dropdown-menu">
                                        <li><a href=""><i class="icon-group"></i> Usuário</a></li>
                                        <li><a href=""><i class="icon-inbox"></i> Ticket</a></li>
                                    </ul>
                                </li>

                            <?php endif; ?>

                            <!--<li>
                                <div class="btn-group">
                                    <form class="form-search">
                                      <div class="input-append">
                                        <input type="text" class="span2 search-query">
                                        <button type="submit" class="btn"> <i class="icon-search"> </i> </button>
                                      </div>
                                    </form>
                                </div>

                            </li>-->

                            <li class="home-user">
                                <p><?php echo $user['name'] ?></p>
                                <?php
                                /*
                                    $directory = 'users'.DIRECTORY_SEPARATOR.$user['id'].DIRECTORY_SEPARATOR;
                                    $iterator = new DirectoryIterator($directory);
                                    foreach ($iterator as $fileinfo) {
                                        if ($fileinfo->isFile()) {
                                            $img = $filenames[$fileinfo->getMTime()] = $fileinfo->getFilename();
                                        }
                                    }
                                    */
                                ?>


                                    <img class="img-rounded" src="../users/<?php //echo $user['id']. "/". $img; ?>" alt="" />
                            </li>

                            <li class="dropdown home-conf">
                                <a class="dropdown-toggle home-link" data-toggle="dropdown" href="#"><i class="icon-cogs"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('user/default', array('controller' => 'user', 'action' => 'edit', 'id' => $user['id'] )); ?>"><i class="icon-inbox"></i> Editar perfil</a></li>
                                    <li><a href="<?php echo $this->url('auth/default', array('controller' => 'auth', 'action' => 'logout')); ?>"><i class=" icon-off"></i> Sair</a></li>
                                </ul>
                            </li>

                        </ul>
                    </div><!--/.nav-collapse -->

                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 by ListService - Andre Jordão, Jesus Vieira </p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript () ?>
    </body>
</html>