<div class="row">

  <div class="span4 box-home">
        <div class="navbar">
          <div class="navbar-inner">
              <p class="navbar-home"><i class="icon-eye-open icon-large"></i> <strong>Ticket's em aberto</strong></p>
          </div>
        </div>

        <div class="thumbnail ticket-home">
            <ul class="unstyled">
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
            </ul>
        </div>
  </div>

  <div class="span4 box-home">
        <div class="navbar">
          <div class="navbar-inner">
              <p class="navbar-home"><i class="icon-wrench icon-large"></i> <strong>Ticket's em andamento</strong></p>
          </div>
        </div>
        <div class="thumbnail ticket-home">
            <ul class="unstyled">
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
            </ul>
        </div>
  </div>

  <div class="span4 box-home">
        <div class="navbar">
          <div class="navbar-inner">
              <p class="navbar-home"><i class="icon-eye-close icon-large"></i> <strong>Ticket's em andamento</strong></p>
          </div>
        </div>
        <div class="thumbnail ticket-home">
            <ul class="unstyled">
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
                <li><a href="#">Mussum ipsum cacilds, vidis litro abertis</a></li>
            </ul>
        </div>
  </div>

</div>