<table class="table table-striped table-condensed table-bordered">
  <caption>Tipo de usuário</caption>
  <thead>
    <tr>
      <th class="span1">#</th>
      <th>Descrição</th>
      <th>Ativo</th>
      <th class="span2">Ação</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->data as $typeUser): ?>
    <tr>
      <th><?php echo $typeUser->getId() ; ?></th>
      <th><?php echo $typeUser->getDescription() ; ?></th>
      <th><?php echo ($typeUser->getActive()) ? '<span class="label label-info">Sim</span>' : '<span class="label">Não</span>'; ?></th>
      <th>
        <div class="btn-toolbar">
          <div class="btn-group">
          <?php if ($typeUser->getId() == 1 || $typeUser->getId() == 2 || $typeUser->getId() == 3): ?>

              <a class="btn active-listservice disabled" href="#" data-toggle="tooltip" data-placement="top" data-original-title="Editar"><i class="icon-pencil"></i></a>
              <a class="btn active-listservice disabled" href="#" data-toggle="tooltip" data-placement="top" data-original-title="Ativar"><i class="icon-ok"></i></a>
              <a class="btn active-listservice disabled" href="#" data-toggle="tooltip" data-placement="top" data-original-title="Deletar"><i class="icon-trash"></i></a>

          <?php else: ?>

              <a class="btn active-listservice" href="<?php echo $this->url('type-user/default', array('controller' => 'type-user', 'action' => 'edit', 'id' => $typeUser->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Editar"><i class="icon-pencil"></i></a>
              <?php if ($typeUser->getActive()): ?>
                  <a class="btn active-listservice" href="<?php echo $this->url('type-user/default', array('controller' => 'type-user', 'action' => 'active', 'id' => $typeUser->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Desativar"><i class="icon-ok"></i></a>
              <?php else: ?>
                  <a class="btn active-listservice" href="<?php echo $this->url('type-user/default', array('controller' => 'type-user', 'action' => 'active', 'id' => $typeUser->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Ativar"><i class="icon-ban-circle"></i></a>
              <?php endif; ?>
              <a class="btn active-listservice" href="<?php echo $this->url('type-user/default', array('controller' => 'type-user', 'action' => 'delete', 'id' => $typeUser->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Deletar"><i class="icon-trash"></i></a>


          <?php endif; ?>

          </div>
        </div>
      </th>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>