<h2>Editar - User</h2>

<?php

$form = $this->form;

$this->formElementErrors ()
        ->setMessageOpenFormat ('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">×</button>')
        ->setMessageCloseString ('</div>')
        ->render ($form);

$form->setAttribute ('action', $this->url ('user/default', array('controller' => 'user', 'action' => 'edit', 'id' => $this->id)));

$form->prepare ();

echo $this->form ()->openTag ($form);

echo $this->formCollection ($form);

echo $this->form ()->closeTag ();

?>