<?php $this->plugin("dateFormat")->setTimezone("America/Campo_Grande")->setLocale("pt_BR");?>
<table class="table table-striped table-condensed table-bordered">
  <caption>Todos os usuários</caption>
  <thead>
    <tr>
      <th class="span1">#</th>
      <th>Nome</th>
      <th>Login</th>
      <th>Registrado</th>
      <th>Categoria</th>
      <th>Ativo</th>
      <th class="span3">Ação</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->data as $user): ?>
    <tr>
      <th><?php echo $user->getId(); ?></th>
      <th><?php echo $user->getName() ; ?></th>
      <th><?php echo $user->getLogin() ; ?></th>
      <th><?php echo $this->dateFormat($user->getDateRegistry(), IntlDateFormatter::SHORT); ?></th>
      <th><?php echo $user->getTypeUse()->getDescription(); ?></th>
      <th><?php echo ($user->getActive()) ? '<span class="label label-info">Sim</span>' : '<span class="label">Não</span>'; ?></th>
      <th>
        <div class="btn-toolbar">
          <div class="btn-group">
            <a class="btn active-listservice" href="<?php echo $this->url('user/default', array('controller' => 'user', 'action' => 'edit', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Editar"><i class="icon-pencil"></i></a>
              <?php if ($user->getActive()): ?>
              <?php if ($user->getTypeUse()->getId() == "1"): ?>
              <a class="btn active-listservice disabled" href="#"><i class="icon-ok"></i></a>
              <?php else: ?>
              <a class="btn active-listservice" href="<?php echo $this->url('user/default', array('controller' => 'user', 'action' => 'active', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Desativar"><i class="icon-ok"></i></a>
              <?php endif; ?>

              <?php else: ?>
              <a class="btn active-listservice" href="<?php echo $this->url('user/default', array('controller' => 'user', 'action' => 'active', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Ativar"><i class="icon-ban-circle"></i></a>
              <?php endif; ?>

              <?php if ($user->getTypeUse()->getId() == "1"): ?>
              <a class="btn active-listservice disabled" href="#"><i class="icon-trash"></i></a>
              <?php else: ?>
              <a class="btn active-listservice" href="<?php echo $this->url('user/default', array('controller' => 'user', 'action' => 'delete', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Deletar"><i class="icon-trash"></i></a>
              <?php endif; ?>
              <?php if ( ($user->getTypeUse()->getId() == "3") OR ($user->getTypeUse()->getId() == "1") ): ?>
                <a class="btn active-listservice disabled" href="#"><i class="icon-unlock"></i></a>
              <?php else: ?>
                <a class="btn active-listservice category-ticket" data-id="<?php echo $user->getId(); ?>" data-nameuser="<?php echo $user->getName() ; ?> - <em>Definir categoria de Ticket</em>" href="<?php echo $this->url('user/default', array('controller' => 'user', 'action' => 'category-ticket', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Definir categoria de Ticket"><i class="icon-unlock"></i></a>
            <?php endif; ?>

          </div>
        </div>
      </th>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>

<script type="text/javascript">
  $(document).ready(function(){
    var name, id;

    $('.category-ticket').click(function(){
      name = $(this).attr("data-nameuser");
      id = $(this).attr("data-id");

      $('#myModalLabel').html(name);

        $('.modal-body').html('<i class="icon-spinner icon-spin icon-large">');
        $('#myModal').on('shown', function () {
            $.ajax({
                type: "GET",
                url: "<?php echo $this->url ('user/default', array('controller' => 'user', 'action' => 'category-ticket')) ?>/"+id,
                success: function(data){
                    $('.modal-body').html(data);
                }
            });
        });

      $('#myModal').modal('show');

      return false;
    });

    $('.exit').click(function(){
      $('#myModal').modal('hide');
    });

  });
</script>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close exit" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"></h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <button class="btn exit" data-dismiss="modal" aria-hidden="true">Fechar</button>
  </div>
</div>