<?php $this->plugin("dateFormat")->setTimezone("America/Campo_Grande")->setLocale("pt_BR");?>
<table class="table table-striped table-condensed table-bordered">
  <caption>Todos os usuários</caption>
  <thead>
    <tr>
      <th class="span1">#</th>
      <th>Nome</th>
      <th>Login</th>
      <th>Registrado</th>
      <th>Ativo</th>
      <th class="span2">Ação</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->data as $user): ?>
    <tr>
      <th><?php echo $user->getId() ; ?></th>
      <th><?php echo $user->getName() ; ?></th>
      <th><?php echo $user->getLogin() ; ?></th>
      <th><?php echo $this->dateFormat($user->getDateRegistry(), IntlDateFormatter::SHORT); ?></th>
      <th><?php echo ($user->getActive()) ? '<span class="label label-info">Sim</span>' : '<span class="label">Não</span>'; ?></th>
      <th>
        <div class="btn-toolbar">
          <div class="btn-group">
            <a class="btn active-listservice" href="<?php echo $this->url('user/default', array('controller' => 'user', 'action' => 'edit', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Editar"><i class="icon-pencil"></i></a>
            <?php if ($user->getActive()): ?>
            <a class="btn active-listservice" href="<?php echo $this->url('user/default', array('controller' => 'user', 'action' => 'active', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Desativar"><i class="icon-ok"></i></a>
            <?php else: ?>
            <a class="btn active-listservice" href="<?php echo $this->url('user/default', array('controller' => 'user', 'action' => 'active', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Ativar"><i class="icon-ban-circle"></i></a>
            <?php endif; ?>
            <a class="btn active-listservice" href="<?php echo $this->url('user/default', array('controller' => 'user', 'action' => 'delete', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Deletar"><i class="icon-trash"></i></a>
          </div>
        </div>
      </th>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>