<div class="row">

  <div class="span4 box-home">
        <div class="navbar">
          <div class="navbar-inner">
              <p class="navbar-home"><i class="icon-group icon-large"></i> <strong>Cadastrar Usuário</strong></p>
          </div>
        </div>

        <div class="thumbnail ticket-home">
            <?php

                $form = $this->form;

                $this->formElementErrors ()
                ->setMessageOpenFormat ('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">×</button>')
                ->setMessageCloseString ('</div>')
                ->render ($form);

                $form->setAttribute ('action', $this->url ('user/default', array('controller' => 'user', 'action' => 'new')));

                $form->prepare ();

                echo $this->form ()->openTag ($form);

                echo $this->formCollection ($form);

                echo $this->form ()->closeTag ();

            ?>
        </div>
  </div>

</div>