<form method="post" action="#">
<?php foreach ($this->data as $value): ?>
    <?php if($this->user == $value['id']):?>
        <label class="radio"><input checked="checked" class="category-check" type="radio" name="user" data-user="<?php echo $this->id; ?>" value="<?php echo $value['id']; ?>"> <?php echo $value['name']; ?></label>
    <?php else: ?>
        <label class="radio"><input class="category-check" type="radio" name="user" data-user="<?php echo $this->id; ?>" value="<?php echo $value['id']; ?>"> <?php echo $value['name']; ?></label>
    <?php endif; ?>
<?php endforeach; ?>
</form>

<script type="text/javascript">
    $(document).ready(function(){

        $('form').submit(function(){return false;});

        $(document).keypress(function (event){
            if(event.which == 13) {return false;}
        });

        $('input[type="radio"]').click(function(){

            var value = $(this).val();
            var id = $(this).attr("data-user");

            $.ajax({
                type: "POST",
                url: "<?php echo $this->url ('ticket/default', array('controller' => 'ticket', 'action' => 'registre-agente')) ?>",
                data: {agente: value, id: id},
                success: function(data){
                    if(data){
                        alert('ERRO: Tente mais tarde!');
                    }
                }
            });
        });
    });
</script>