<?php $this->plugin("dateFormat")->setTimezone("America/Campo_Grande")->setLocale("pt_BR");?>
<table class="table table-striped table-condensed table-bordered">
  <caption>Meus Ticket's</caption>
  <thead>
    <tr>
      <th class="span1">#</th>
      <th>Titulo</th>
      <th>Solicitante</th>
      <th>Data abertura</th>
      <th>Data estimada</th>
      <th>Status</th>
      <th>Categoria</th>
      <th class="span2">Ação</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->data as $user): ?>
    <tr>
      <th><?php echo $user->getId() ; ?></th>
      <th><?php echo $user->getTitle() ; ?></th>
      <th><?php echo $user->getSought() ; ?></th>
      <th><?php echo $this->dateFormat($user->getDateBegin(), IntlDateFormatter::SHORT); ?></th>
      <th><?php echo $this->dateFormat($user->getDateEstimated(), IntlDateFormatter::SHORT); ?></th>
      <th><?php echo $user->getCategoryTicket()->getDescription() ; ?></th>
      <th><?php echo ($user->getActive()) ? '<span class="label label-info">Sim</span>' : '<span class="label">Não</span>'; ?></th>
      <th>
        <div class="btn-toolbar">
          <div class="btn-group">
            <a class="btn active-listservice" href="<?php echo $this->url('interaction/default', array('controller' => 'interaction', 'action' => 'new', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Interagir"><i class="icon-pencil"></i></a>

            <?php if ($this->typeUser == "Adm"): ?>
            <?php if ($user->getActive()): ?>
            <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'active', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Desativar"><i class="icon-ok"></i></a>
            <?php else: ?>
            <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'active', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Ativar"><i class="icon-ban-circle"></i></a>
            <?php endif; ?>
            <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'delete', 'id' => $user->getId())); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Deletar"><i class="icon-trash"></i></a>
          <?php endif; ?>
          </div>
        </div>
      </th>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>