<?php $user = $this->UserIdentity("LS"); ?>

<?php
//\Zend\Debug\Debug::dump($user);die;

?>


<table class="table table-striped table-condensed table-bordered">
  <caption>Meus Ticket's</caption>
  <thead>
    <tr>
      <th class="span1">#</th>
      <th>Titulo</th>
      <th>Solicitante</th>
      <th>Data abertura</th>
      <th>Previsão</th>
      <th>Categoria</th>
      <th>Status</th>
      <th>Ação</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->data as $ticket): ?>
    <tr>
      <th><?php echo $ticket['id']; ?></th>
      <th><?php echo $ticket['title']; ?></th>
      <th><?php echo $ticket['sought']; ?></th>
      <th><?php echo $ticket['date_begin']; ?></th>
      <th><?php echo $ticket['date_estimated']; ?></th>
      <th><?php echo $ticket['category']; ?></th>
      <th><?php echo $ticket['status']; ?></th>
      <th>
        <div class="btn-toolbar">
          <div class="btn-group">
            <a class="btn active-listservice" href="<?php echo $this->url('interaction/default', array('controller' => 'interaction', 'action' => 'new', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Interagir"><i class="icon-pencil"></i></a>

            <?php if (($user['id'] == 1) && ($user['category'] == 'Administrador')): ?>

              <a class="btn active-listservice datepicke" href="<?php echo $ticket['id']; ?>" data-toggle="tooltip" data-placement="top" data-original-title="Definir Previsão" data-date="<?php echo date('d-m-Y');?>" data-date-format="dd-mm-yyyy"><i class="icon-time"></i></a>
              <a class="btn active-listservice agente" href="<?php echo $ticket['id']; ?>" data-toggle="tooltip" data-placement="top" data-original-title="Definir Agente" ><i class="icon-group"></i></a>
              <?php if ($ticket['active']): ?>
                <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'active', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Desativar"><i class="icon-ok"></i></a>
              <?php else: ?>
                <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'active', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Ativar"><i class="icon-ban-circle"></i></a>
              <?php endif; ?>
            <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'delete', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Deletar"><i class="icon-trash"></i></a>
          <?php endif; ?>
          </div>
        </div>
      </th>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>


<script type="text/javascript">
  $(document).ready(function(){

    $('.agente').click(function(){

      var id = $(this).attr('href');

      $('#myModalLabel').html(name);

      $.ajax({
          type: "GET",
          url: "<?php echo $this->url ('ticket/default', array('controller' => 'ticket', 'action' => 'agente')) ?>/"+id,
          success: function(data){
            $('.modal-body').html(data);
          }
      });

      $('#myModal').modal('show');

      return false;
    });

    $('.exit').click(function(){
      $('#myModal').modal('hide');
    });

  });
</script>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close exit" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"></h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <button class="btn exit" data-dismiss="modal" aria-hidden="true">Fechar</button>
  </div>
</div>





