<?php $user = $this->UserIdentity("LS"); ?>

<table class="table table-striped table-condensed table-bordered">
  <caption>Meus Ticket's</caption>
  <thead>
    <tr>
      <th class="span1">#</th>
      <th>Titulo</th>
      <th>Solicitante</th>
      <th>Data abertura</th>
      <th>Previsão</th>
      <th>Prioridade</th>
      <th>Categoria</th>
      <th class="span2">Status</th>
      <th>Ação</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($this->data as $ticket): ?>
    <tr>
      <th><?php echo $ticket['id']; ?></th>
      <th><?php echo $ticket['title']; ?></th>
      <th><?php echo $ticket['sought']; ?></th>
      <th><?php echo $ticket['date_begin']; ?></th>
      <th><?php echo $ticket['date_estimated']; ?></th>
      <th><?php echo $ticket['priority']; ?></th>
      <th><?php echo $ticket['category']; ?></th>
      <th><?php echo $ticket['status']; ?></th>

      <?php if (($user['id'] == 1) && ($user['category'] == 'Administrador')): ?>
      <th style="width: 280px">
      <?php else: ?>
        <th style="width: 80px">
      <?php endif; ?>

        <div class="btn-toolbar">
          <div class="btn-group">

            <?php if (! is_null($ticket['date_end']) || $ticket['active'] != 1 ):?>
                <a class="btn active-listservice disabled" href="#" data-toggle="tooltip" data-placement="top" data-original-title="Interagir"><i class="icon-pencil"></i></a>
            <?php else: ?>
                <a class="btn active-listservice" href="<?php echo $this->url('interaction/default', array('controller' => 'interaction', 'action' => 'new', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Interagir"><i class="icon-pencil"></i></a>
            <?php endif; ?>

            <?php if (($user['id'] == 1) && ($user['category'] == 'Administrador')): ?>

              <a class="btn active-listservice datepicke" href="<?php echo $ticket['id']; ?>" data-toggle="tooltip" data-placement="top" data-original-title="Definir Previsão" data-date="<?php echo date('d-m-Y');?>" data-date-format="dd-mm-yyyy"><i class="icon-time"></i></a>
              <a class="btn active-listservice agente" href="#myModal" data-toggle="modal" data-id="<?php echo $ticket['id']; ?>" data-toggle="tooltip" data-placement="top" data-original-title="Definir Agente" ><i class="icon-group"></i></a>

                <a class="btn active-listservice priority" href="#myModal" data-toggle="modal" data-id="<?php echo $ticket['id']; ?>" data-toggle="tooltip" data-placement="top" data-original-title="Definir Prioridade" ><i class="icon-tags"></i></a>

                <?php if (is_null($ticket['date_end'])):?>
                    <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'close', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Fechar Ticket" ><i class="icon-eye-open"></i></a>
                <?php else: ?>
                    <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'close', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Abrir Ticket" ><i class="icon-eye-close"></i></a>
                <?php endif; ?>

              <?php if ($ticket['active']): ?>
                <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'active', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Desativar"><i class="icon-ok"></i></a>
              <?php else: ?>
                <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'active', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Ativar"><i class="icon-ban-circle"></i></a>
              <?php endif; ?>
            <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'delete', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Deletar"><i class="icon-trash"></i></a>
          <?php else: ?>

                <?php if (is_null($ticket['date_end'])):?>
                    <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'close', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Fechar Ticket" ><i class="icon-eye-open"></i></a>
                <?php else: ?>
                    <a class="btn active-listservice" href="<?php echo $this->url('ticket/default', array('controller' => 'ticket', 'action' => 'close', 'id' => $ticket['id'])); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Abrir Ticket" ><i class="icon-eye-close"></i></a>
                <?php endif; ?>

            <?php endif; ?>
          </div>
        </div>
      </th>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<?php echo $this->paginationControl($this->data, 'Sliding', 'paginator'); ?>


<script type="text/javascript">
  $(document).ready(function(){

    /*Define agente*/
    $('.agente').click(function(){


      var id = $(this).attr('data-id');

        $('#myModalLabel').html("Definir Agente");
        $('.modal-body').html('<i class="icon-spinner icon-spin icon-large">');


        $('#myModal').on('shown', function () {

            $.ajax({
                type: "GET",
                url: "<?php echo $this->url ('ticket/default', array('controller' => 'ticket', 'action' => 'agente')) ?>/"+id,
                success: function(data){
                    $('.icon-spinner').fadeOut('slow');
                    $('.modal-body').fadeIn('slow').html(data);
                }
            });
        });
    });

    /*Define Prioridade*/
    $('.priority').click(function(){

      var id = $(this).attr('data-id');

      $('#myModalLabel').html("Definir Prioridade");
      $('.modal-body').html('<i class="icon-spinner icon-spin icon-large">');

        $('#myModal').on('shown', function () {
          $.ajax({
              type: "GET",
              url: "<?php echo $this->url ('ticket/default', array('controller' => 'ticket', 'action' => 'priority')) ?>/"+id,
              success: function(data){
                  $('.icon-spinner').fadeOut('slow');
                  $('.modal-body').fadeIn('slow').html(data);
              }
          });
        });
    });


      $('#myModal').on('hidden', function () {
          $('#myModalLabel').html();
          $('.modal-body').html();
          window.location.reload();
      })

  });
</script>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"></h3>
  </div>
  <div class="modal-body"></div>
  <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
  </div>
</div>





