<?php

namespace LSUser\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByLoginAndPassword($login, $password) {

        $user = $this->findBy(array('login' => $login));

        if ($user) {
            $hashSenha = $user[0]->encryptPassword($password);

            if ($hashSenha == $user[0]->getPassword()) {
                return $user;
            }
            else
                return false;
        }
        else
            return false;
    }
}
