<?php echo $this->doctype(); ?>
<html class="bg-black">
    <head lang="en">
        <meta charset="UTF-8">
        <?php echo $this->headTitle($this->translate('Login')); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/AdminLTE.css')
                        ->prependStylesheet($this->basePath() . '/css/ionicons.min.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>
    </head>
    <body class="bg-black">

        <div class="form-box" id="login-box">
            <div class="header"><?php echo $this->translate('Sign In'); ?></div>

            <?php
                $form = $this->loginForm;
                $form->prepare();
                $form->setAttribute('action', $this->url('zfcuser/login'));
                $form->setAttribute('method', 'post');
            ?>

            <?php echo $this->form()->openTag($form) ?>

                <div class="body bg-gray">
                    <?php echo $this->formElementErrors($form->get('identity')) ?>

                    <div class="form-group">
                        <?php echo $this->formInput($form->get('identity')->setAttributes(array(
                            'class' => 'form-control',
                            'placeholder' => 'User ID'
                        ))) ?>
                    </div>

                    <div class="form-group">
                        <?php echo $this->formInput($form->get('credential')->setAttributes(array(
                            'class' => 'form-control',
                            'placeholder' => 'Password'
                        ))) ?>
                    </div>

                    <?php if ($this->redirect): ?>
                        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                    <?php endif ?>

                    <div class="footer">
                        <?php echo $this->formButton($form->get('submit')->setAttributes(array('class' => 'btn bg-olive btn-block'))); ?>

                        <p><a href="<?php echo $this->url('user'); ?>/recovery-password"><?php echo $this->translate('I forgot my password'); ?></a></p>

                        <?php if ($this->enableRegistration) : ?>
                        <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
                        <?php endif; ?>
                    </div>
                </div>

            <?php echo $this->form()->closeTag() ?>

        </div>

        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', 'text/javascript', array('conditional' => 'lt IEz 9',))
            ->prependFile('https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ; ?>
    </body>
</html>
