<?php echo $this->doctype(); ?>
<html class="bg-black">
    <head lang="en">
        <meta charset="UTF-8">
        <?php echo $this->headTitle($this->translate('Login')); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/AdminLTE.css')
                        ->prependStylesheet($this->basePath() . '/css/ionicons.min.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>
    </head>
    <body class="bg-black">
        <div class="form-box" id="login-box">

            <div class="header"><?php echo $this->translate('Register'); ?></div>

            <?php
                if (!$this->enableRegistration) {
                    print "Registration is disabled";
                    return;
                }
                $form = $this->registerForm;
                $form->prepare();
                $form->setAttribute('action', $this->url('zfcuser/register'));
                $form->setAttribute('method', 'post');
                $form->setAttribute('role', 'form');

                    $this->formElementErrors()
                    ->setMessageOpenFormat('<li class="text-danger">')
                    ->setMessageCloseString('</li>')->render($form);
            ?>

            <?php echo $this->form()->openTag($form) ?>
                    <div style="padding: 10px 20px; color: #444" class=" bg-gray">

                    <?php $x=0; foreach ($form as $element): ?>
                        <?php if ($element instanceof Zend\Form\Element\Button): ?>
                        </div>
                            <div class="footer">
                                <?php echo $this->formButton($element->setAttributes(array('class' => 'btn bg-olive btn-block'))) ?>
                                <a href="<?php echo $this->url('zfcuser/login'); ?>" class="text-center">I already have a membership</a>
                            </div>
                        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                            <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
                        <?php else: ?>
                            <div class="form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">
                                <label class="control-label" <?php if($this->formElementErrors($element)) echo ' for="inputError'.+$x.'"' ?>>
                                    <?php if($this->formElementErrors($element)) echo '<i class="fa fa-times-circle-o"></i> ' ?><?php echo $element->getLabel() ?>
                                </label>
                                <?php $attr = ['class' => 'form-control']; if($this->formElementErrors($element)) { $id = "inputError{$x}"; $attr = ['class' => 'form-control', 'id' => $id];} ?>
                                <?php echo $this->formInput($element->setAttributes($attr)) . $this->formElementErrors($element) ?>
                            </div>
                        <?php endif ?>
                    <?php $x++; endforeach ?>

                    <?php if ($this->redirect): ?>
                        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                    <?php endif ?>

            <?php echo $this->form()->closeTag() ?>

        </div>
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js', 'text/javascript', array('conditional' => 'lt IEz 9',))
            ->prependFile('https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ; ?>
    </body>
</html>
